const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_QUERY: "INVALID_QUERY",
  INVALID_ID: "INVALID_ID",
  LOG_NOT_FOUND: "LOG_NOT_FOUND",
  WRITE_TOKEN_MISSING: "WRITE_TOKEN_MISSING",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  JWT_SECRET_MISSING: "JWT_SECRET_MISSING",
  INVALID_SESSION: "INVALID_SESSION",
  USER_INACTIVE: "USER_INACTIVE",
  DEPENDENCY_CONTRACT_ERROR: "DEPENDENCY_CONTRACT_ERROR",
};

module.exports = ERROR_CODES;
